2020-06-24 20:57:53,449 : INFO : scraper : Running __kaggleSearch
2020-06-24 20:57:55,745 : INFO : scraper : Running __awsSearch
2020-06-24 20:57:59,810 : ERROR : scraper : Error in displaySearch
Traceback (most recent call last):
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 19, in __init__
    self.writeOutput(*kgl_info,*aws_info)
TypeError: writeOutput() takes 0 positional arguments but 14 were given
2020-06-24 21:00:35,557 : INFO : scraper : Running __kaggleSearch
2020-06-24 21:00:38,267 : INFO : scraper : Running __awsSearch
2020-06-24 21:18:39,715 : INFO : scraper : Running __kaggleSearch
2020-06-24 21:18:42,444 : INFO : scraper : __kaggleSearch returns 20
2020-06-24 21:18:42,444 : INFO : scraper : Running __awsSearch
2020-06-24 21:18:46,450 : INFO : scraper : __awsSearch returns 14
2020-06-24 21:19:32,277 : INFO : scraper : Running __kaggleSearch
2020-06-24 21:19:33,491 : INFO : scraper : __kaggleSearch returns 0 results
2020-06-24 21:19:33,491 : INFO : scraper : Running __awsSearch
2020-06-24 21:19:36,825 : INFO : scraper : __awsSearch returns 14 results
2020-07-08 20:22:24,002 : INFO : scraper : Running __kaggleSearch
2020-07-08 20:22:27,864 : INFO : scraper : __kaggleSearch returns 0 results
2020-07-08 20:22:27,865 : INFO : scraper : Running __awsSearch
2020-07-08 20:22:38,079 : INFO : scraper : __awsSearch returns 16 results
2020-07-14 19:53:01,777 : INFO : scraper : Running __kaggleSearch
2020-07-14 19:53:03,180 : INFO : scraper : __kaggleSearch returns 0 results
2020-07-14 19:53:03,181 : INFO : scraper : Running __awsSearch
2020-07-14 19:53:07,873 : INFO : scraper : __awsSearch returns 19 results
2020-07-14 19:53:37,131 : INFO : scraper : Running __kaggleSearch
2020-07-14 19:53:39,135 : INFO : scraper : __kaggleSearch returns 20 results
2020-07-14 19:53:39,135 : INFO : scraper : Running __awsSearch
2020-07-14 19:53:42,988 : INFO : scraper : __awsSearch returns 19 results
2020-07-14 19:57:23,869 : INFO : scraper : Running __kaggleSearch
2020-07-14 19:57:23,869 : ERROR : scraper : Error in displaySearch
Traceback (most recent call last):
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 17, in retrieveLinks
    self.kgl_info = self.__kaggleSearch(term = self.keyword)
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 62, in __kaggleSearch
    browser.get(kgl_url)
NameError: name 'kgl_url' is not defined
2020-07-14 19:58:06,462 : INFO : scraper : Running __kaggleSearch
2020-07-14 19:58:06,462 : ERROR : scraper : Error in displaySearch
Traceback (most recent call last):
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 17, in retrieveLinks
    self.kgl_info = self.__kaggleSearch(term = self.keyword)
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 62, in __kaggleSearch
    browser.get(kgl_url)
NameError: name 'kgl_url' is not defined
2020-07-14 19:59:03,353 : INFO : scraper : Running __kaggleSearch
2020-07-14 19:59:05,006 : ERROR : scraper : Error in displaySearch
Traceback (most recent call last):
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 17, in retrieveLinks
    self.kgl_info = self.__kaggleSearch(term = self.keyword)
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 65, in __kaggleSearch
    browser.find_element_by_xpath(search_box).send_keys(term)
  File "C:\Users\Computer\Anaconda3\envs\ds_py38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Computer\Anaconda3\envs\ds_py38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Computer\Anaconda3\envs\ds_py38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Computer\Anaconda3\envs\ds_py38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: Given xpath expression "//input[contains@class,"MuiInputBase-input"]" is invalid: SyntaxError: The expression is not a legal expression.

2020-07-14 20:04:36,160 : INFO : scraper : Running __kaggleSearch
2020-07-14 20:04:37,415 : INFO : scraper : __kaggleSearch returns 0 results
2020-07-14 20:04:37,415 : INFO : scraper : Running __awsSearch
2020-07-14 20:04:41,444 : INFO : scraper : __awsSearch returns 19 results
2020-07-14 20:30:08,603 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-14 20:30:11,836 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 20 results
2020-07-14 20:30:11,836 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-14 20:30:18,834 : INFO : scraper : Search on https://registry.opendata.aws/ returns 499 results
2020-07-21 20:44:11,865 : ERROR : scraper : Error in displaySearch
Traceback (most recent call last):
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 19, in retrieveLinks
    self.kgl_info = self.__Search(term = self.keyword, url = self.kgl_url, linksPath = self.kgl_xpath, searchBoxPath = self.kgl_box)
AttributeError: 'displaySearch' object has no attribute 'kgl_url'
2020-07-21 20:46:06,693 : ERROR : scraper : Error in displaySearch
Traceback (most recent call last):
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 20, in retrieveLinks
    self.kgl_info = self.__Search(term = self.keyword, url = self.kgl_url, linksPath = self.kgl_xpath, searchBoxPath = self.kgl_box)
AttributeError: 'displaySearch' object has no attribute 'kgl_url'
2020-07-21 20:48:29,838 : ERROR : scraper : Error in displaySearch
Traceback (most recent call last):
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 20, in retrieveLinks
    self.kgl_info = self.__Search(term = self.keyword, url = self.kgl_url, linksPath = self.kgl_xpath, searchBoxPath = self.kgl_box)
AttributeError: 'displaySearch' object has no attribute 'kgl_url'
2020-07-21 20:51:50,391 : ERROR : scraper : Error in displaySearch
Traceback (most recent call last):
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 20, in retrieveLinks
    self.kgl_info = self.__Search(term = self.keyword, url = self.kgl_url, linksPath = self.kgl_xpath, searchBoxPath = self.kgl_box)
AttributeError: 'displaySearch' object has no attribute 'kgl_url'
2020-07-21 21:07:05,699 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-21 21:07:08,120 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 20 results
2020-07-21 21:07:08,120 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-21 21:07:13,390 : INFO : scraper : Search on https://registry.opendata.aws/ returns 504 results
2020-07-21 21:08:35,632 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-21 21:08:38,477 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 0 results
2020-07-21 21:08:38,477 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-21 21:08:44,105 : INFO : scraper : Search on https://registry.opendata.aws/ returns 504 results
2020-07-21 21:32:26,721 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-21 21:32:29,319 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 0 results
2020-07-21 21:32:29,319 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-21 21:32:34,653 : INFO : scraper : Search on https://registry.opendata.aws/ returns 504 results
2020-07-21 21:32:50,172 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-21 21:32:50,172 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-21 21:32:52,640 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 0 results
2020-07-21 21:32:52,640 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 0 results
2020-07-21 21:32:52,640 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-21 21:32:52,640 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-21 21:32:58,204 : INFO : scraper : Search on https://registry.opendata.aws/ returns 504 results
2020-07-21 21:32:58,204 : INFO : scraper : Search on https://registry.opendata.aws/ returns 504 results
2020-07-21 21:41:03,794 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-21 21:41:05,827 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 20 results
2020-07-21 21:41:05,827 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-21 21:41:11,072 : INFO : scraper : Search on https://registry.opendata.aws/ returns 504 results
2020-07-21 21:44:15,130 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-21 21:44:17,325 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 20 results
2020-07-21 21:44:17,326 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-21 21:44:22,561 : INFO : scraper : Search on https://registry.opendata.aws/ returns 504 results
2020-07-21 21:46:17,437 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-21 21:46:20,452 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 0 results
2020-07-21 21:46:20,453 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-21 21:46:25,605 : INFO : scraper : Search on https://registry.opendata.aws/ returns 504 results
2020-07-21 21:46:52,185 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-21 21:46:52,185 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-21 21:46:54,871 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 20 results
2020-07-21 21:46:54,871 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 20 results
2020-07-21 21:46:54,871 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-21 21:46:54,871 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-21 21:47:00,285 : INFO : scraper : Search on https://registry.opendata.aws/ returns 504 results
2020-07-21 21:47:00,285 : INFO : scraper : Search on https://registry.opendata.aws/ returns 504 results
2020-07-23 20:12:33,372 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-23 20:12:35,370 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 20 results
2020-07-23 20:12:35,370 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-23 20:12:41,139 : INFO : scraper : Search on https://registry.opendata.aws/ returns 507 results
2020-07-23 20:16:10,236 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-23 20:16:12,092 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 20 results
2020-07-23 20:16:12,092 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-23 20:16:17,916 : INFO : scraper : Search on https://registry.opendata.aws/ returns 507 results
2020-07-23 20:19:27,217 : INFO : scraper : Connection to {url} can be established.
2020-07-23 20:19:27,404 : INFO : scraper : Connection to {url} can be established.
2020-07-23 20:19:27,404 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-23 20:19:29,856 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 0 results
2020-07-23 20:19:29,856 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-23 20:19:34,410 : INFO : scraper : Search on https://registry.opendata.aws/ returns 507 results
2020-07-23 20:21:50,400 : INFO : scraper : Connection to https://www.kaggle.com/datasets can be established.
2020-07-23 20:21:50,600 : INFO : scraper : Connection to https://registry.opendata.aws/ can be established.
2020-07-23 20:21:50,600 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-23 20:21:53,679 : INFO : scraper : Search on https://www.kaggle.com/datasets returns 0 results
2020-07-23 20:21:53,680 : INFO : scraper : Running search on https://registry.opendata.aws/
2020-07-23 20:21:59,370 : INFO : scraper : Search on https://registry.opendata.aws/ returns 507 results
2020-07-23 20:23:42,631 : ERROR : scraper : Connection to https://www.kaggle.com/datasets cannot be established
2020-07-23 20:23:42,646 : ERROR : scraper : Connection to https://registry.opendata.aws/ cannot be established
2020-07-23 20:23:42,646 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-23 20:23:42,700 : ERROR : scraper : Error in displaySearch
Traceback (most recent call last):
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 21, in retrieveLinks
    self.kgl_info = self.__Search(term = self.keyword, url = self.kgl_url, linksPath = self.kgl_xpath, searchBoxPath = self.kgl_box)
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 67, in __Search
    browser.get(url)
  File "C:\Users\Computer\Anaconda3\envs\ds_py38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Computer\Anaconda3\envs\ds_py38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Computer\Anaconda3\envs\ds_py38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=dnsNotFound&u=https%3A//www.kaggle.com/datasets&c=UTF-8&d=We%20can%E2%80%99t%20connect%20to%20the%20server%20at%20www.kaggle.com.

2020-07-23 20:29:14,273 : ERROR : scraper : Connection to https://www.kaggle.com/datasets cannot be established
2020-07-23 20:29:14,275 : ERROR : scraper : Connection to https://registry.opendata.aws/ cannot be established
2020-07-23 20:29:14,275 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-23 20:29:14,341 : ERROR : scraper : Error in displaySearch
Traceback (most recent call last):
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 21, in retrieveLinks
    self.kgl_info = self.__Search(term = self.keyword, url = self.kgl_url, linksPath = self.kgl_xpath, searchBoxPath = self.kgl_box)
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 67, in __Search
    browser.get(url)
  File "C:\Users\Computer\Anaconda3\envs\ds_py38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Computer\Anaconda3\envs\ds_py38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Computer\Anaconda3\envs\ds_py38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=dnsNotFound&u=https%3A//www.kaggle.com/datasets&c=UTF-8&d=We%20can%E2%80%99t%20connect%20to%20the%20server%20at%20www.kaggle.com.

2020-07-23 20:30:14,132 : ERROR : scraper : Connection to https://www.kaggle.com/datasets cannot be established
2020-07-23 20:30:14,147 : ERROR : scraper : Connection to https://registry.opendata.aws/ cannot be established
2020-07-23 20:30:14,147 : INFO : scraper : Running search on https://www.kaggle.com/datasets
2020-07-23 20:30:14,201 : ERROR : scraper : Error in displaySearch
Traceback (most recent call last):
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 21, in retrieveLinks
    self.kgl_info = self.__Search(term = self.keyword, url = self.kgl_url, linksPath = self.kgl_xpath, searchBoxPath = self.kgl_box)
  File "c:\Users\Computer\ds_device\ds_device\scraper.py", line 67, in __Search
    browser.get(url)
  File "C:\Users\Computer\Anaconda3\envs\ds_py38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Computer\Anaconda3\envs\ds_py38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Computer\Anaconda3\envs\ds_py38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=dnsNotFound&u=https%3A//www.kaggle.com/datasets&c=UTF-8&d=We%20can%E2%80%99t%20connect%20to%20the%20server%20at%20www.kaggle.com.

